Algoritmo "raiz"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : UniCesumar
// Descrição   : calcular a raiz quadrada.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/05/2022
Var
   raiz: real
   num, quadrado: inteiro

Inicio

Escreva("Informe um número inteiro:")
leia(num)
raiz <- sqrt(num)
quadrado <- sqr(num)
escreva("A raiz quadrada é:", raiz)
escreva("O número elevado ao quadrado é:", quadrado)

Fimalgoritmo