Algoritmo "numero"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aapresentar o antecessor e o sucessor de um número digitado
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/05/2022
Var
   numero : inteiro
Inicio

escreva("digite um numero inteiro: ")
leia(numero)

escreva("Numero anterior: ", numero - 1)
escreva(", Numero posterior: ", numero + 1)

Fimalgoritmo