Algoritmo "triagulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Unicesumar
// Descrição   : calcular a area de um triangulo
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/05/2022
Var

   base, altura, area : real


Inicio

escreva("Digite o valor da Base do triangulo: ")
leia(base)

escreva("Digite o valor da altura do triangulo: ")
leia(altura)

area <- (base * altura) / 2

escreva("A Area total do triangulo é: ", area)

Fimalgoritmo